<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Stock-quote-last-price</name>
   <tag></tag>
   <elementGuidId>13017233-f553-40d3-abdc-00e970e6aec1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#stock-quote-last-price</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='stock-quote-last-price']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;248.17&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c1a1c27c-c4fd-4b10-ba4f-3dec0a3cd9da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>stock-quote-last-price</value>
      <webElementGuid>37660a0b-2ffd-4021-8180-cd6c3ebe195b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>248.17</value>
      <webElementGuid>71b18ded-dd81-44c9-bbce-272d9340edaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;stock-quote-last-price&quot;)</value>
      <webElementGuid>df117c56-f69d-4c31-af1f-6e20fa875bd9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='stock-quote-last-price']</value>
      <webElementGuid>0d989830-06ce-4812-92b7-8d4a745318aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
